[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"

[context.production]
  command = "npx prisma generate && npm run build"

[context.deploy-preview]
  command = "npx prisma generate && npm run build"

[context.branch-deploy]
  command = "npx prisma generate && npm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-src 'self' https://*.itch.io https://*.sketchfab.com https://*.youtube.com https://*.vimeo.com; object-src 'none'; base-uri 'self'; form-action 'self';"

# Preview routes with different CSP
[[headers]]
  for = "/api/preview/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-src 'self' https://*.itch.io https://*.sketchfab.com https://*.youtube.com https://*.vimeo.com; object-src 'none'; base-uri 'self'; form-action 'self';"
